spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_social_network
    username: username
    passsword: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform:
  mail:
    host: localhost
    port: 1025
    username: abel
    password: abel
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 8D2A546F7B6C413D9E3F6A215F7A4C635D784128753A6B344D53703A456E7F21
      expiration: 86400000
